mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8&parseTime=true
  db: submission_db
  user: root
  password: 123456
  log_level: dev
logger:
  level: info
  prefix: '[RG]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: "0.0.0.0"
  port: 8084
  env: release