# k8s/notification-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: host
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: password
        - name: USER_SERVICE_URL
          value: "http://user-service.default.svc.cluster.local:8081" 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5